services:
  auth-postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5433:5432"
    volumes:
      - auth-pg-data:/var/lib/postgresql/data

  auth-redis:
    image: redis:8
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes

  auth-kafka:
    image: soldevelo/kafka:4.1
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@auth-kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    ports:
      - "9092:9092"

  kafka-ui:
    image: kafbat/kafka-ui:latest
    depends_on:
      auth-kafka:
        condition: service_started
    environment:
      KAFKA_CLUSTERS_0_NAME: auth
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: auth-kafka:9092
      DYNAMIC_CONFIG_ENABLED: "true"
    ports:
      - "8090:8080"

volumes:
  auth-pg-data:
