services:
  mpc-postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: mpc_db
      POSTGRES_USER: mpc_user
      POSTGRES_PASSWORD: mpc_pass
    ports:
      - "5435:5432"
    volumes:
      - mpc-pg-data:/var/lib/postgresql/data

  mpc-kafka:
    image: soldevelo/kafka:4.1
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@mpc-kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    ports:
      - "9094:9092"

  kafka-ui:
    image: kafbat/kafka-ui:latest
    depends_on:
      mpc-kafka:
        condition: service_started
    environment:
      KAFKA_CLUSTERS_0_NAME: mpc
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: mpc-kafka:9092
      DYNAMIC_CONFIG_ENABLED: "true"
    ports:
      - "8090:8080"

volumes:
  mpc-pg-data:
