services:
  twofa-postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: twofa_db
      POSTGRES_USER: twofa_user
      POSTGRES_PASSWORD: twofa_pass
    ports:
      - "5434:5432"
    volumes:
      - twofa-pg-data:/var/lib/postgresql/data

  twofa-redis:
    image: redis:8
    ports:
      - "6381:6379"
    command: redis-server --appendonly yes

  twofa-kafka:
    image: soldevelo/kafka:4.1
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@twofa-kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    ports:
      - "9093:9092"

  kafka-ui:
    image: kafbat/kafka-ui:latest
    depends_on:
      twofa-kafka:
        condition: service_started
    environment:
      KAFKA_CLUSTERS_0_NAME: twofa
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: twofa-kafka:9092
      DYNAMIC_CONFIG_ENABLED: "true"
    ports:
      - "8090:8080"

volumes:
  twofa-pg-data:
